version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    container_name: server_test
    ports:
    - '3006:3006'
    volumes:
      - ./:/app
      - /app/node_modules
  redis:
    image: redis
    command: redis-server
    container_name: redis_test
    ports:
    - '6379:6379'
